name: ci
on:
  push:
    # paths:
    #   - 'foo/**'

defaults:
  run:
    working-directory: foo

jobs:
  foo_filter:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.filter.outputs.foo }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            foo:
              - 'foo/**'

  foo_lint_test_typecheck:
    needs: foo_filter
    if: ${{ needs.foo_filter.outputs.foo == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.11.0'

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ’…ğŸ¼ lint
        run: npm run lint

      - name: ğŸš¨ test
        run: npm run test:ok
        # run: npm run test

      - name: âœ… type check
        run: npm run typecheck