name: ci
on:
  pull_request:
    paths:
      - 'foo/**'

defaults:
  run:
    working-directory: foo

jobs:
  foo_lint_test_typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.11.0'

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ’…ğŸ¼ lint
        run: npm run lint

      - name: ğŸš¨ test
        run: npm run test:ok
        # run: npm run test

      - name: âœ… type check
        run: npm run typecheck